use springblog_db;

insert into products (name, price_in_cents) values ('Argalis', 527);
insert into products (name, price_in_cents) values ('Magnificent frigate bird', 7443);
insert into products (name, price_in_cents) values ('Indian star tortoise', 8185);
insert into products (name, price_in_cents) values ('Bee-eater (unidentified)', 1034);
insert into products (name, price_in_cents) values ('Fox, cape', 5369);
insert into products (name, price_in_cents) values ('Gull, lava', 5560);
insert into products (name, price_in_cents) values ('Trumpeter, green-winged', 7673);
insert into products (name, price_in_cents) values ('Bontebok', 2408);
insert into products (name, price_in_cents) values ('Squirrel, arctic ground', 6117);
insert into products (name, price_in_cents) values ('Laughing kookaburra', 9527);
insert into products (name, price_in_cents) values ('Boa, columbian rainbow', 6551);
insert into products (name, price_in_cents) values ('Thomson''s gazelle', 7992);
insert into products (name, price_in_cents) values ('Andean goose', 3033);
insert into products (name, price_in_cents) values ('Impala', 3134);
insert into products (name, price_in_cents) values ('Jacana, african', 569);
insert into products (name, price_in_cents) values ('Cat, civet', 9346);
insert into products (name, price_in_cents) values ('Deer, red', 1286);
insert into products (name, price_in_cents) values ('Openbill, asian', 6256);
insert into products (name, price_in_cents) values ('Sidewinder', 2090);
insert into products (name, price_in_cents) values ('Violet-crested turaco', 4312);
insert into products (name, price_in_cents) values ('Dromedary camel', 9531);
insert into products (name, price_in_cents) values ('Grizzly bear', 9602);
insert into products (name, price_in_cents) values ('Eastern quoll', 9253);
insert into products (name, price_in_cents) values ('Malay squirrel (unidentified)', 2645);
insert into products (name, price_in_cents) values ('Pine snake (unidentified)', 5025);
insert into products (name, price_in_cents) values ('Sea birds (unidentified)', 8914);
insert into products (name, price_in_cents) values ('Cardinal, black-throated', 5201);
insert into products (name, price_in_cents) values ('Porcupine, prehensile-tailed', 55);
insert into products (name, price_in_cents) values ('Fox, grey', 7091);
insert into products (name, price_in_cents) values ('Common turkey', 5833);
insert into products (name, price_in_cents) values ('Cobra (unidentified)', 518);
insert into products (name, price_in_cents) values ('Lizard, collared', 1961);
insert into products (name, price_in_cents) values ('Steenbok', 5014);
insert into products (name, price_in_cents) values ('Yellow-throated sandgrouse', 2051);
insert into products (name, price_in_cents) values ('Monitor, water', 8102);
insert into products (name, price_in_cents) values ('Cat, native', 3777);
insert into products (name, price_in_cents) values ('Zorro, common', 9479);
insert into products (name, price_in_cents) values ('Squirrel glider', 7570);
insert into products (name, price_in_cents) values ('Racer snake', 6558);
insert into products (name, price_in_cents) values ('Arctic ground squirrel', 9552);
insert into products (name, price_in_cents) values ('Deer, mule', 5761);
insert into products (name, price_in_cents) values ('Indian tree pie', 2361);
insert into products (name, price_in_cents) values ('Cat, african wild', 3554);
insert into products (name, price_in_cents) values ('Three-banded plover', 3912);
insert into products (name, price_in_cents) values ('Goose, knob-nosed', 7529);
insert into products (name, price_in_cents) values ('Ovenbird', 2032);
insert into products (name, price_in_cents) values ('Vulture, white-rumped', 8774);
insert into products (name, price_in_cents) values ('American bison', 3607);
insert into products (name, price_in_cents) values ('Pied butcher bird', 3879);
insert into products (name, price_in_cents) values ('Phalarope, grey', 9665);
