insert into products (name, priceInCents) values ('Eagle, african fish', 19);
insert into products (name, priceInCents) values ('Great horned owl', 1);
insert into products (name, priceInCents) values ('Baboon, olive', 80);
insert into products (name, priceInCents) values ('Northern elephant seal', 8);
insert into products (name, priceInCents) values ('Common wallaroo', 34);
insert into products (name, priceInCents) values ('Seal, northern fur', 13);
insert into products (name, priceInCents) values ('Monkey, vervet', 2);
insert into products (name, priceInCents) values ('Violet-crested turaco', 61);
insert into products (name, priceInCents) values ('Herring gull', 64);
insert into products (name, priceInCents) values ('White-cheeked pintail', 95);
insert into products (name, priceInCents) values ('Skink, african', 78);
insert into products (name, priceInCents) values ('White-throated toucan', 55);
insert into products (name, priceInCents) values ('Lapwing (unidentified)', 100);
insert into products (name, priceInCents) values ('Common green iguana', 24);
insert into products (name, priceInCents) values ('Monitor lizard (unidentified)', 63);
insert into products (name, priceInCents) values ('Alligator, mississippi', 16);
insert into products (name, priceInCents) values ('Paca', 86);
insert into products (name, priceInCents) values ('Vulture, griffon', 17);
insert into products (name, priceInCents) values ('Chacma baboon', 98);
insert into products (name, priceInCents) values ('Cat, european wild', 72);
insert into products (name, priceInCents) values ('Hippopotamus', 27);
insert into products (name, priceInCents) values ('Kingfisher, pied', 43);
insert into products (name, priceInCents) values ('Sage hen', 32);
insert into products (name, priceInCents) values ('Ibis, sacred', 2);
insert into products (name, priceInCents) values ('Tokay gecko', 68);
insert into products (name, priceInCents) values ('Blue wildebeest', 20);
insert into products (name, priceInCents) values ('Pale-throated three-toed sloth', 1);
insert into products (name, priceInCents) values ('Grenadier, common', 34);
insert into products (name, priceInCents) values ('Lesser masked weaver', 59);
insert into products (name, priceInCents) values ('Red-necked phalarope', 8);
insert into products (name, priceInCents) values ('Eagle, bald', 25);
insert into products (name, priceInCents) values ('Asian water dragon', 74);
insert into products (name, priceInCents) values ('Crimson-breasted shrike', 31);
insert into products (name, priceInCents) values ('White-tailed jackrabbit', 93);
insert into products (name, priceInCents) values ('Arctic ground squirrel', 44);
insert into products (name, priceInCents) values ('Lizard, blue-tongued', 23);
insert into products (name, priceInCents) values ('Snake, eastern indigo', 42);
insert into products (name, priceInCents) values ('Malabar squirrel', 81);
insert into products (name, priceInCents) values ('Blesbok', 86);
insert into products (name, priceInCents) values ('Bee-eater, carmine', 21);
insert into products (name, priceInCents) values ('Monkey, rhesus', 70);
insert into products (name, priceInCents) values ('Common melba finch', 39);
insert into products (name, priceInCents) values ('Savanna fox', 61);
insert into products (name, priceInCents) values ('Possum, pygmy', 85);
insert into products (name, priceInCents) values ('Klipspringer', 91);
insert into products (name, priceInCents) values ('Toddy cat', 41);
insert into products (name, priceInCents) values ('Horned lark', 2);
insert into products (name, priceInCents) values ('Lemur, brown', 33);
insert into products (name, priceInCents) values ('Tailless tenrec', 60);
insert into products (name, priceInCents) values ('Arctic hare', 77);
insert into products (name, priceInCents) values ('Springhare', 96);
insert into products (name, priceInCents) values ('Blue catfish', 44);
insert into products (name, priceInCents) values ('Lizard, blue-tongued', 85);
insert into products (name, priceInCents) values ('Ring-tailed gecko', 73);
insert into products (name, priceInCents) values ('Asiatic wild ass', 34);
insert into products (name, priceInCents) values ('Javanese cormorant', 79);
insert into products (name, priceInCents) values ('Monitor lizard (unidentified)', 82);
insert into products (name, priceInCents) values ('Snowy sheathbill', 81);
insert into products (name, priceInCents) values ('Monkey, red howler', 42);
insert into products (name, priceInCents) values ('Four-striped grass mouse', 32);
insert into products (name, priceInCents) values ('Paddy heron (unidentified)', 36);
insert into products (name, priceInCents) values ('Springbuck', 41);
insert into products (name, priceInCents) values ('Brazilian tapir', 7);
insert into products (name, priceInCents) values ('Waterbuck, common', 28);
insert into products (name, priceInCents) values ('Heron, yellow-crowned night', 84);
insert into products (name, priceInCents) values ('Striated heron', 14);
insert into products (name, priceInCents) values ('Lizard (unidentified)', 92);
insert into products (name, priceInCents) values ('Collared lemming', 98);
insert into products (name, priceInCents) values ('Vervet monkey', 43);
insert into products (name, priceInCents) values ('Vicuna', 96);
insert into products (name, priceInCents) values ('Hottentot teal', 11);
insert into products (name, priceInCents) values ('Hare, arctic', 92);
insert into products (name, priceInCents) values ('Bandicoot, long-nosed', 40);
insert into products (name, priceInCents) values ('Warthog', 67);
insert into products (name, priceInCents) values ('Bird, bare-faced go away', 32);
insert into products (name, priceInCents) values ('Goose, greylag', 97);
insert into products (name, priceInCents) values ('Bohor reedbuck', 5);
insert into products (name, priceInCents) values ('Egret, snowy', 16);
insert into products (name, priceInCents) values ('Silver-backed jackal', 24);
insert into products (name, priceInCents) values ('Pied crow', 79);
insert into products (name, priceInCents) values ('Macaw, red and blue', 1);
insert into products (name, priceInCents) values ('Blue-breasted cordon bleu', 84);
insert into products (name, priceInCents) values ('Marabou stork', 82);
insert into products (name, priceInCents) values ('Lemur, grey mouse', 13);
insert into products (name, priceInCents) values ('Malagasy ground boa', 85);
insert into products (name, priceInCents) values ('Bonnet macaque', 39);
insert into products (name, priceInCents) values ('Savannah deer', 61);
insert into products (name, priceInCents) values ('Heron, yellow-crowned night', 82);
insert into products (name, priceInCents) values ('Dassie', 71);
insert into products (name, priceInCents) values ('Grebe, little', 77);
insert into products (name, priceInCents) values ('Dusky gull', 38);
insert into products (name, priceInCents) values ('Baleen whale', 82);
insert into products (name, priceInCents) values ('Australian brush turkey', 78);
insert into products (name, priceInCents) values ('Avocet, pied', 24);
insert into products (name, priceInCents) values ('Pied kingfisher', 11);
insert into products (name, priceInCents) values ('Cormorant, javanese', 13);
insert into products (name, priceInCents) values ('Woodpecker, red-headed', 13);
insert into products (name, priceInCents) values ('Javanese cormorant', 26);
insert into products (name, priceInCents) values ('Andean goose', 13);
insert into products (name, priceInCents) values ('Lion, african', 81);
