package com.example.codeup.springblog.repositories;

import com.example.codeup.springblog.model.Product;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;

import java.util.List;

//public interface ProductRepository extends JpaRepository <Product,Long>{
//}
public interface ProductRepository extends JpaRepository<Product, Long> {

    // Can use derived queries to create a wide variety of methods that will be generated by Hibernate
    List<Product> getProductsByIdAfter(long id);

    List<Product> getProductByNameEndsWithIgnoreCase(String str);

    Product getFirstByPriceInCents(int priceInCents);

    // Can use JPQL to define more specific queries
    @Query("SELECT p.name FROM Product p ORDER BY p.name DESC")
    List<String> getProductNames();

    // Can create a query using MySQL SQL syntax
    @Query(nativeQuery = true, value = "SELECT name FROM products p ORDER BY name DESC")
    List<String> getProductNamesNative();

}
